### ISSUE TITLE
Question on URIs ending

### ISSUE THREAD

**Issue by OceaneAbrard** [OP-TED/ted-rdf-mapping-eforms#22] opened 2024-06-07 12:25 UTC
Hello,

Following a discussion we had this morning with @cristianvasquez and Natalie Muric, we wanted to clarify with you some aspects of the construction of the URIs. Especially, we were wondering to what does the hash part at the end of an URI correspond. For example, in the following URI, to what does the end hash (**6dcsBnuV4FTNoRpTZHckqN**) corresponds to, and why does it repeat itself in those two URIs:

http://data.europa.eu/a4g/resource/id_6c52efe3-fcc5-4411-9b9d-2e5132fcf7dc_Procedure_6dcsBnuV4FTNoRpTZHckqN
http://data.europa.eu/a4g/resource/id_6c52efe3-fcc5-4411-9b9d-2e5132fcf7dc_ProcedureIdentifier_6dcsBnuV4FTNoRpTZHckqN

but not in these other ones (**Hu2nD8nFQkA5CPSQ43KMRD**):

http://data.europa.eu/a4g/resource/id_6c52efe3-fcc5-4411-9b9d-2e5132fcf7dc_ProcedurePurpose_Hu2nD8nFQkA5CPSQ43KMRD
http://data.europa.eu/a4g/resource/id_6c52efe3-fcc5-4411-9b9d-2e5132fcf7dc_ProcedureIdentifier_Hu2nD8nFQkA5CPSQ43KMRD

Fyi, all these URIs come from the same notice and are all related to the same epo:Procedure.

Thanks in advance,
Océane

**Comment by schivmeister** [comment] 2024-06-07 14:13
Hi, thank you for raising this question. Let me reproduce here our URI scheme, which somehow got lost among all of our communications:

- The eForms RML mappings use the URI scheme `{ns}id_{notice-id}_{concept}_{trailer}`, where
  - `{ns}` is a base namespace, in this case `http://data.europa.eu/a4g/resource/`
  - `{concept}` is either (i) an ontology fragment label or (ii) source element label, with a suffix or prefix
  - `{trailer}` is either (i) an ID value (if the resource has one) or (ii) an _online_ computed, deterministic hash
  - Root concepts such as `epo:Notice` end up to only the `{concept}`

Expanding on some of the components for further clarity:

- Whether a `concept` is an ontology fragment or source element label, and whether this label has a suffix (rarely) or prefix, depends on the subjective (human) evaluation of whether only having the class name is sufficient hint of what the URI represents.
- The trailer, when a hash, is computed (seeded) with the XPath named element (e.g. `cbc:ID`) or (often relative) path (e.g. `path(cbc:ID)`) of what is being mapped, and therefore lends a unique identity to the URI. This yields reproducible URIs across RML TripleMaps, in case a resource needed to be instantiated at different XPaths, for whatever purpose.
  - A Lot or any other resource with an inherent ID, would simply have its `cbc:ID` value as the trailer, for e.g. `epd:id_14549263-b47b-4e59-96a1-2d0d13e19343_Lot_LOT-0001`, which is very useful for linking purposes at orthogonal XPaths (e.g. wherever an `id-ref` is concerned, that ID could simply be used to produce a linkable URI without having to navigate XPaths).
  - Any other resource where there is no inherent ID would have a hash that is unique to the XPath it represents, e.g. an `epo:Purpose` instance, if instantiated at different XPaths for associating different attributes, would have the same URI across those instantiations, resulting in one unique instance and no duplication due to multiple mappings.
    - The `adms:Identifier`, although having an ID, may still get a hash instead of ID in its trailer, as it may not have a short ID that is sensible to use/read (however we may not have enforced this rule strongly)

I regret that I cannot describe examples with the resources you cite, as you have not cited a data source. All URIs will vary across notices, as the ID of a notice marks the beginning, and any (unique) part of the notice, the ending. However, what I can say is that in your example, we can see instances of:

- 1 x `epo:Procedure`
- 1 x `epo:Purpose`
- 2 x `adms:Identifier` ("ID" and "Internal ID", where the ID gets the same hash as the Procedure as it is instantiated at the same XPath)

I hope this helps answer your question, let us know.

Note: Wherever _URI_ is mentioned, [IRI](https://www.w3.org/2001/Talks/0912-IUC-IRI/paper.html#:~:text=In%20principle%2C%20the%20definition%20of,us%2Dascii%20characters%20in%20URIs) is meant. Also, the generation of hashes is done _online_ against a remote HTTP web API endpoint offering this function, during transformation (which can otherwise be an offline process).

**Comment by OceaneAbrard** [comment] 2024-06-07 15:09
Thank you for your response! Here is a link to the notice I'm referring to, it would be helpful if you could provide a complementary explanation with this specific example:

https://ted.europa.eu/en/notice/-/detail/329908-2024

If I understood correctly, the reason why the trailer in the two following examples is the same is because they are also instantiated with the same XPath?

http://data.europa.eu/a4g/resource/id_6c52efe3-fcc5-4411-9b9d-2e5132fcf7dc_ProcedurePurpose_Hu2nD8nFQkA5CPSQ43KMRD
http://data.europa.eu/a4g/resource/id_6c52efe3-fcc5-4411-9b9d-2e5132fcf7dc_ProcedureIdentifier_Hu2nD8nFQkA5CPSQ43KMRD

Thanks again for your help,
Océane

**Comment by csnyulas** [comment] 2024-06-07 19:54
That is correct @OceaneAbrard !

The reason the `{trailer}` of those two instances are the same is that they are both generated from the `/*/cac:ProcurementProject` XPath, which is unique to the Procedure. If that XPath would correspond to a repeatable node, we would have different hashes for each matching of it, such as `/ContractAwardNotice/cac:ProcurementProject[1]`, `/ContractAwardNotice/cac:ProcurementProject[2]`, etc. But that is not the case for the XML element providing description of the procedure. Although we use the same `{trailer}` in these IRIs, representing the position of the source element in the XML file, the RDF instances will have distinct IRIs thanks to the `{concept}` component, which is different and is related to the type of the instance in order to help human interpretability (`ProcedurePurpose` vs `ProcedureIdentifier`).

I hope this is clear now. Let us know if it is not.

**Comment by schivmeister** [comment] 2024-06-10 14:44
@OceaneAbrard please let us know if further clarification is required or if we can close this, thank you.

**Comment by OceaneAbrard** [comment] 2024-06-18 15:52
Sorry, I was out of office last week due to a personal emergency, I just saw your notifications. Thank you for your answers, this clears things out for me regarding the construction of the URIs.
If I can suggest, I think it would be useful to have this construction process for the URIs described in a bit more lasting way. It could get lost amongst the other posts on the Github discussion I fear.

**Comment by schivmeister** [comment] 2024-06-19 11:53
@OceaneAbrard indeed, we have added this information to the README, if you can please review https://github.com/OP-TED/ted-rdf-mapping-eforms/pull/26

**Closed as completed by schivmeister** 2024-06-19 11:53 UTC
Labels: documentation, question
