### ISSUE TITLE
Missing epo:hasLegalBasis for certain sdk versions

### ISSUE THREAD

**Issue by cristianvasquez** [OP-TED/ted-rdf-mapping-eforms#52] opened 2024-09-02 12:30 UTC
Hello, 

Notice 00152054-2024 constains a `cbc:RegulatoryDomain` referring to the Procedure Legal Basis, but no corresponding value for `epo:hasLegalBasis` was found

```xml
<cbc:RegulatoryDomain>32014L0023</cbc:RegulatoryDomain>
```

Source XML: https://ted.europa.eu/en/notice/152054-2024/xml

This issue has been reported in the following cases:

- EF14 for SDK version 1.7, 1.8 and 1.10  (00152266-2024, 00152054-2024, 00191175-2024)
- EF15 for SDK version 1.7, 1.8 and 1.10 (00140913-2024, 00179143-2024, 00144555-2024)
- EF16 for SDK version 1.6 and 1.7 (00127096-2024, 00126821-2024)
- EF19 for SDK version 1.6, 1.8 and 1.10  (00129735-2024, 00129801-2024, 00128154-2024)

Some notices contain `epo:hasLegalBasis`, for example EF12 for SDK version 1.10

**Comment by schivmeister** [comment] 2024-09-02 18:16
Thanks for reporting. The issue is that some notices, such as PriorInformation, do not have the toplevel `cac:TenderingProcess`. This throws off the corresponding mapping as it is under a wrong iterator (it should not be at the iterator of the TenderingProcess but the root).

**Comment by muricna** [comment] 2024-09-03 10:57
This is not clear to me as  only  EF14 is a PIN used as a call for competition, EF15 is a qualification system and both EF 16 and EF 19 are competition notices.

**Comment by schivmeister** [comment] 2024-09-17 09:00
@muricna that is indeed correct. however, we are _not_ able to reproduce the reported issue for most of the cited notices, i.e. those other than the PIN (EF14) and the qualification system (EF15).

@cristianvasquez it would be good if you can confirm how you came to report the competition notices. Perhaps, there was a misunderstanding/misinterpretation, or another underlying issue that is being exposed?

**Comment by OceaneAbrard** [comment] 2024-09-17 13:03
Hello, 
I verified again the notices that Cristian has reported using the mapping present in the Tags 1.0.0-rc.7 and the epo:hasLegalBasis is still missing from the following notices: 
EF14 for SDK version 1.7, 1.8 and 1.10  (00152266-2024, 00152054-2024, 00191175-2024)
EF15 for SDK version 1.7, 1.8 and 1.10 (00140913-2024, 00179143-2024, 00144555-2024)
EF19 for SDK version 1.6, 1.8 and 1.10  (00129490-2024, 00129801-2024, 00128154-2024)

I verified the EF16 that were reported, and these ones are no longer missing the epo:hasLegalBasis.

**Comment by schivmeister** [comment] 2024-09-18 08:37
@OceaneAbrard Thank you for confirming. It is expected that EF19 will still exhibit this issue, as they appear to be competition notices that do _not_ have a tendering process defined at the root of the notice, and the mapping was not written to deal with that. This will be fixed. Only EF16 is not reproducible, in that case, and will be assumed to not be affected.

P.S: Note that it would be best if all testing in this context is carried out against the tag `1.0.0-rc.6`, upon which this ticket is and the next CN release will be based, as `rc.7` is a CAN release only.

**Closed as completed** 2024-09-20 19:35 UTC
Labels: bug
